version: "3.9"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src
    command: sh -c "cd app && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true
    env_file: .env
